/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_company_engine_ConceptEngine */

#ifndef _Included_com_company_ceandroid_ConceptEngine
#define _Included_com_company_ceandroid_ConceptEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_ceandroid_ConceptEngine
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_company_ceandroid_ConceptEngine_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_company_ceandroid_ConceptEngine
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_ceandroid_ConceptEngine_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
